default: &default
  adapter: postgresql
  encoding: utf8  
  pool: 5
  
development:
  <<: *default
  database: de1tcq6mjo5v1d
  pool: 5
  username: qtcocbsxqqkryz
  password: 8321a5ae43a45861de9b02aecaab3c5f237369342d0716f1d3ad6e85f2977ebd
  host:     ec2-50-19-86-139.compute-1.amazonaws.com
  sslmode:  require
  
production:
  <<: *default
  database: de1tcq6mjo5v1d
  pool: 5
  username: qtcocbsxqqkryz
  password: 8321a5ae43a45861de9b02aecaab3c5f237369342d0716f1d3ad6e85f2977ebd
  host:     ec2-50-19-86-139.compute-1.amazonaws.com
  sslmode:  require
  